# Generated by Django 3.2.12 on 2023-05-10 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification_code',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='verification_code',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 7, 32, 43, 27864)),
        ),
        migrations.AlterField(
            model_name='verification_code',
            name='expiry_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 7, 35, 43, 27922)),
        ),
    ]
